### ISSUE TITLE
Error with pool payments.

### ISSUE THREAD

**Issue by cancabron** [meritlabs/CoiniumServ#12]
Ey! Im trying to run a pool.

All works fine except the payments. Ive tried a clean db, change OS (ubuntu 16 & 18), change db collation... But I always get the same error:

**[Error] [PaymentProcessor] [Merit] An error occured while trying to execute payment; "Account has insufficient funds".**

Any idea to solve this? The pool account has +70MRT on it. The wallet is unlocked (no password, if I add password I get the response that the wallet is locket "add your walletpassphrase first...").

I would like to create a new pool for the community, but it is being impossible with the issue of payments.

Thanks!

**Comment by tonypizzicato** [comment]
@cancabron please, try to build from this branch https://github.com/meritlabs/merit-pool/pull/11. that should help

**Comment by cancabron** [comment]
Ok, thanks for your fast reply! I will post the results! 👍

**Comment by cancabron** [comment]
Solved! Thanks @tonypizzicato :)
